# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='公告内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '知识页公告',
                'verbose_name_plural': '知识页公告',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '博客文章类别',
                'verbose_name_plural': '博客文章类别',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='文章标题')),
                ('body', mdeditor.fields.MDTextField(verbose_name='正文内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='最后修改时间')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='文章摘要')),
                ('img', models.ImageField(blank=True, upload_to='img', verbose_name='展示图')),
                ('fav', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ['-create_time'],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
        migrations.CreateModel(
            name='ShareOthers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='链接标题')),
                ('href', models.URLField(verbose_name='链接')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分享的其他文章',
                'verbose_name_plural': '分享的其他文章',
            },
        ),
        migrations.CreateModel(
            name='ShareProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='链接标题')),
                ('href', models.URLField(verbose_name='链接')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分享的编程文章',
                'verbose_name_plural': '分享的编程文章',
            },
        ),
        migrations.CreateModel(
            name='ShareTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='标签名字')),
                ('tag_text', models.CharField(max_length=256, verbose_name='标签代码')),
                ('tag_color', models.CharField(max_length=20, verbose_name='颜色代码')),
            ],
            options={
                'verbose_name': '分享链接的标签样式',
                'verbose_name_plural': '分享链接的标签样式',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '标签云',
                'verbose_name_plural': '标签云',
            },
        ),
        migrations.AddField(
            model_name='shareprogram',
            name='tag1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag1', to='users.ShareTag'),
        ),
        migrations.AddField(
            model_name='shareprogram',
            name='tag2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag2', to='users.ShareTag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='users.Tag', verbose_name='标签'),
        ),
    ]
